title: 'Simple Theme'
default_lang: en
author:
  name: 'Diome Nike Potot'
  email: system-admin@redstarishwebdesign.com
taxonomies:
  - category
  - tag
metadata:
  description: 'This theme was develop with love by Halcyon Web Design'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
