@extends:
  type: default
  context: blueprints://pages

visible: true
form:
  validation: loose 
  fields:
    tabs:
      type: tabs
      active: 1
 
      fields:
        advanced: 
            unset@: true
            type: ignore
        content:
            type: tab
            title: PLUGIN_ADMIN.CONTENT
            fields:
                folder:
                  type: text
                #   label: PLUGIN_ADMIN.FOLDER_NAME
                  label: Slug
                  ordering@: 2
                  style: vertical
                  validate:
                    rule: slug
                header.subtitle:
                  type: text
                  label: Subtitle
                  style: vertical
                  ordering@: 3
                header.featured:
                    label: Featured
                    help: Determines if this service will be featured in homepage. 
                    type: toggle 
                    highlight: 1 
                    default: 0
                    ordering@: 4
                    style: vertical 
                    options:
                        1: Enabled
                        0: Disabled
                    validate:
                        type: bool
                header.visible:
                  type: toggle
                  style: vertical
                #   toggleable: true
                  label: PLUGIN_ADMIN.VISIBLE
                  help: PLUGIN_ADMIN.VISIBLE_HELP
                  highlight: 1
                  default: 1
                  ordering@: 5
                  options:
                    1: PLUGIN_ADMIN.ENABLED
                    0: PLUGIN_ADMIN.DISABLED
                  validate:
                    type: bool 
                header.featured_image:
                  name: 'featured_image'
                  type: file
                  label: Featured Image
                  type: file
                  destination: '@self'
                  description: Only .png, .jpg, .jpeg file types are allowed.
                  multiple: false
                  style: vertical 
                  help: The image the will be used in homepage.
                  accept:
                    - .png
                    - .jpg
                    - .jpeg
                  ordering@: 6
                  
                header.fieldset.summary: 
                    ordering@: 7
                    type: fieldset
                    title: Short Description 
                    info: (collapsible)
                    icon: comments
                    collapsed: false
                    collapsible: true 
                    fields:
                        header.shortdesc:
                          label: Summary
                          type: markdown
                          validate:
                            type: textarea
                            required: true  
                content:
                    label: Content
                    type: tinymce
                    ordering@: 8
                    validate:
                      type: textarea
                
                header.slider:
                  label: Slider 
                  type: file
                  destination: '@self'
                  description: Only .png, .jpg, .jpeg file types are allowed.
                  multiple: true
                  style: vertical
                  accept:
                    - .png
                    - .jpg
                    - .jpeg
                  ordering@: 9
                  
                header.media_order:
                    unset@: true
                    type: ignore
                    
                
        